import styles from './page.module.css';

const STACK = [
  { layer: 'Orchestration', items: ['LangGraph 0.2', 'Multi-agent StateGraph', 'SSE streaming'] },
  { layer: 'Intelligence', items: ['Claude Sonnet 4.6', 'QLoRA fine-tuned Qwen2.5-3B', 'Semantic re-ranking'] },
  { layer: 'Memory', items: ['pgvector (Neon)', 'Episodic memory store', 'Cosine similarity search'] },
  { layer: 'Backend', items: ['FastAPI', 'SQLAlchemy async', 'Psycopg3'] },
  { layer: 'Frontend', items: ['Next.js 14 App Router', 'TypeScript', 'CSS Modules'] },
];

const AGENTS = [
  { name: 'opportunity_hunter', color: 'sky', desc: 'Finds ML/AI internships using pgvector semantic similarity against your skill profile.' },
  { name: 'gap_detector', color: 'iris', desc: 'Compares your resume skills against job requirements and surfaces specific gaps to close.' },
  { name: 'roadmap_planner', color: 'mint', desc: 'Generates time-boxed learning plans calibrated to your current level and target role.' },
  { name: 'resume_analyzer', color: 'sky', desc: 'Extracts and categorises skills from PDF resumes, building a semantic skill graph.' },
  { name: 'interview_coach', color: 'iris', desc: 'Runs contextual mock interviews on ML system design and behavioural questions.' },
  { name: 'application_tracker', color: 'mint', desc: 'Maintains pipeline state across wishlist, applied, interviewing, offer, and rejected.' },
];

export default function AboutPage() {
  return (
    <div className={styles.page}>
      <div className={styles.container}>

        {/* Header */}
        <section className={styles.hero}>
          <span className={`eyebrow ${styles.eyebrow}`}>About Mitra</span>
          <h1 className={`display-1 ${styles.title}`}>
            A multi-agent career<br />
            <span className="heading-gradient">intelligence system</span>
          </h1>
          <p className={`body-lg ${styles.sub}`}>
            Mitra is a portfolio project built at IIT Madras demonstrating production-grade agentic AI:
            multi-agent orchestration, semantic memory, skill gap detection, and fine-tuned models,
            all in a single domain-specific system for ML/AI internship pipelines.
          </p>
        </section>

        {/* Agent grid */}
        <section className={styles.section}>
          <h2 className={`display-2 ${styles.sectionTitle}`}>6 Specialised Agents</h2>
          <p className="body-md" style={{ marginTop: 12, maxWidth: 520 }}>
            Each agent is an isolated async node in a LangGraph StateGraph. The graph is rebuilt
            per request to bind the DB session: no global state, no module-level caches.
          </p>

          <div className={styles.agentGrid}>
            {AGENTS.map(a => (
              <div key={a.name} className={styles.agentCard}>
                <span className={`${styles.agentName} ${styles[`color_${a.color}`]}`}>
                  {a.name}
                </span>
                <p className={styles.agentDesc}>{a.desc}</p>
              </div>
            ))}
          </div>
        </section>

        {/* Tech stack */}
        <section className={styles.section}>
          <h2 className={`display-2 ${styles.sectionTitle}`}>Technology Stack</h2>

          <div className={styles.stackGrid}>
            {STACK.map(s => (
              <div key={s.layer} className={styles.stackCard}>
                <span className={styles.stackLayer}>{s.layer}</span>
                <ul className={styles.stackItems}>
                  {s.items.map(i => (
                    <li key={i} className={styles.stackItem}>{i}</li>
                  ))}
                </ul>
              </div>
            ))}
          </div>
        </section>

        {/* Key design decisions */}
        <section className={styles.section}>
          <h2 className={`display-2 ${styles.sectionTitle}`}>Key Design Decisions</h2>

          <div className={styles.decisionList}>
            {[
              {
                title: 'Graph rebuilt per request',
                body: 'build_graph(db) is called inside the SSE endpoint so each request gets a fresh graph with a bound async DB session, avoiding session sharing across concurrent requests.',
              },
              {
                title: 'Single LLM gateway',
                body: 'All Claude calls route through services/llm_client.py. No agent imports anthropic directly, making model swaps and rate-limit handling a one-file change.',
              },
              {
                title: 'Psycopg3 + pgvector',
                body: 'Psycopg3 (asyncio) gives cleaner integration with pgvector than asyncpg. Embeddings are generated by a sentence-transformers singleton loaded once at startup.',
              },
              {
                title: 'QLoRA fine-tuned classifier',
                body: 'Qwen2.5-3B fine-tuned with QLoRA on 500 synthetic training pairs to classify intent before routing, keeping the main LLM call focused on generation, not classification.',
              },
            ].map(d => (
              <div key={d.title} className={styles.decision}>
                <h3 className={styles.decisionTitle}>{d.title}</h3>
                <p className={styles.decisionBody}>{d.body}</p>
              </div>
            ))}
          </div>
        </section>

      </div>
    </div>
  );
}
