"""
Seed realistic Indian ML/AI internship opportunities into the database.
Run: python -m db.seed_opportunities
"""
import asyncio
import sys
from pathlib import Path

# Allow running from backend/ directory
sys.path.insert(0, str(Path(__file__).parent.parent))

from app.config import settings
from app.database import AsyncSessionLocal, init_db
from app.models.db import Opportunity
from app.services import embedding_service

OPPORTUNITIES = [
    {
        "title": "Machine Learning Intern",
        "company": "Sarvam AI",
        "location": "Bangalore, India",
        "description": "Work on fine-tuning and evaluating LLMs for Indian languages. Build evaluation pipelines, contribute to production inference systems, and help improve multilingual models.",
        "required_skills": ["Python", "PyTorch", "LLMs", "Fine-tuning", "HuggingFace", "CUDA"],
        "type": "internship",
        "stipend": "₹60,000/month",
        "deadline": "2026-07-31",
        "url": "https://sarvam.ai/careers",
    },
    {
        "title": "AI Research Intern",
        "company": "Krutrim",
        "location": "Bangalore, India",
        "description": "Research and develop next-gen LLM capabilities for Indian languages. Focus areas include pre-training, RLHF, and multilingual NLP.",
        "required_skills": ["Python", "PyTorch", "NLP", "Research", "LLMs", "RLHF"],
        "type": "internship",
        "stipend": "₹80,000/month",
        "deadline": "2026-08-15",
        "url": "https://olakrutrim.com/careers",
    },
    {
        "title": "ML Engineer Intern",
        "company": "Glean",
        "location": "Remote / Bangalore",
        "description": "Build semantic search and retrieval systems. Work with embeddings, vector databases, and ranking algorithms at scale.",
        "required_skills": ["Python", "Embeddings", "Vector DBs", "Elasticsearch", "FastAPI", "RAG"],
        "type": "internship",
        "stipend": "$3,000/month",
        "deadline": "2026-07-15",
        "url": "https://glean.com/careers",
    },
    {
        "title": "MLOps Intern",
        "company": "Fractal Analytics",
        "location": "Mumbai / Pune, India",
        "description": "Design and implement ML pipelines, model monitoring, and deployment infrastructure. Experience with cloud platforms and containerization preferred.",
        "required_skills": ["Python", "Docker", "Kubernetes", "MLflow", "GCP", "CI/CD", "FastAPI"],
        "type": "internship",
        "stipend": "₹45,000/month",
        "deadline": "2026-09-01",
        "url": "https://fractal.ai/careers",
    },
    {
        "title": "Data Science Intern",
        "company": "Tiger Analytics",
        "location": "Chennai / Bangalore",
        "description": "Work on forecasting models, causal inference experiments, and recommendation systems for Fortune 500 clients.",
        "required_skills": ["Python", "Scikit-learn", "Pandas", "SQL", "Statistics", "Time Series", "Causal Inference"],
        "type": "internship",
        "stipend": "₹40,000/month",
        "deadline": "2026-08-30",
        "url": "https://tigeranalytics.com/careers",
    },
    {
        "title": "Recommender Systems Intern",
        "company": "Meesho",
        "location": "Bangalore, India",
        "description": "Build and improve product recommendation algorithms. Work on collaborative filtering, neural rankers, and A/B experimentation at scale.",
        "required_skills": ["Python", "PyTorch", "Recommender Systems", "Collaborative Filtering", "Spark", "SQL"],
        "type": "internship",
        "stipend": "₹70,000/month",
        "deadline": "2026-07-20",
        "url": "https://meesho.io/careers",
    },
    {
        "title": "NLP Research Intern",
        "company": "AI4Bharat (IIT Madras)",
        "location": "Chennai, India (On-site)",
        "description": "Contribute to open-source NLP tools for Indian languages. Work on ASR, MT, and language model pre-training.",
        "required_skills": ["Python", "PyTorch", "NLP", "HuggingFace", "Research", "Transformers"],
        "type": "research",
        "stipend": "₹25,000/month",
        "deadline": "2026-08-01",
        "url": "https://ai4bharat.iitm.ac.in",
    },
    {
        "title": "Computer Vision Intern",
        "company": "Ather Energy",
        "location": "Bangalore, India",
        "description": "Develop perception algorithms for electric two-wheelers. Work on object detection, depth estimation, and edge deployment with ONNX/TensorRT.",
        "required_skills": ["Python", "OpenCV", "PyTorch", "ONNX", "TensorRT", "Object Detection", "CUDA"],
        "type": "internship",
        "stipend": "₹50,000/month",
        "deadline": "2026-07-31",
        "url": "https://atherenergy.com/careers",
    },
    {
        "title": "Generative AI Intern",
        "company": "Quantiphi",
        "location": "Mumbai / Remote",
        "description": "Build production-grade RAG systems, LLM agents, and evaluation pipelines for enterprise clients on AWS and GCP.",
        "required_skills": ["Python", "LangChain", "RAG", "LLMs", "AWS", "GCP", "Vector DBs", "FastAPI"],
        "type": "internship",
        "stipend": "₹55,000/month",
        "deadline": "2026-09-15",
        "url": "https://quantiphi.com/careers",
    },
    {
        "title": "ML Research Fellow",
        "company": "Microsoft Research India",
        "location": "Bangalore, India",
        "description": "6-month research fellowship. Work directly with researchers on NLP, fairness in ML, or systems for ML. Publish-quality research expected.",
        "required_skills": ["Python", "PyTorch", "Research", "Deep Learning", "NLP", "Statistics", "Paper Writing"],
        "type": "fellowship",
        "stipend": "₹1,00,000/month",
        "deadline": "2026-06-30",
        "url": "https://www.microsoft.com/en-us/research/lab/microsoft-research-india/",
    },
    {
        "title": "AI Infrastructure Intern",
        "company": "Sprinklr",
        "location": "Gurugram / Remote",
        "description": "Work on distributed training infrastructure, model serving optimization, and GPU cluster management.",
        "required_skills": ["Python", "CUDA", "PyTorch", "Distributed Training", "Docker", "Kubernetes"],
        "type": "internship",
        "stipend": "₹65,000/month",
        "deadline": "2026-08-31",
        "url": "https://sprinklr.com/careers",
    },
    {
        "title": "Agentic AI Intern",
        "company": "yellow.ai",
        "location": "Bangalore, India",
        "description": "Build multi-agent conversational AI systems. Work with LangGraph, tool use, memory systems, and evaluation frameworks.",
        "required_skills": ["Python", "LangGraph", "LangChain", "LLMs", "Agents", "FastAPI", "RAG"],
        "type": "internship",
        "stipend": "₹50,000/month",
        "deadline": "2026-08-15",
        "url": "https://yellow.ai/careers",
    },
    {
        "title": "SWE Intern (ML Platform)",
        "company": "Flipkart",
        "location": "Bangalore, India",
        "description": "Build internal ML platform tooling: feature stores, experiment tracking, and model registry. Scale to millions of models.",
        "required_skills": ["Python", "Go", "Spark", "Kafka", "MLflow", "SQL", "System Design"],
        "type": "internship",
        "stipend": "₹80,000/month",
        "deadline": "2026-07-15",
        "url": "https://flipkartcareers.com",
    },
    {
        "title": "Smart India Hackathon 2026",
        "company": "Ministry of Education (Govt of India)",
        "location": "Multiple Cities",
        "description": "36-hour national hackathon solving real government problems. Team of 6. Prize pool ₹1 lakh per problem statement.",
        "required_skills": ["Python", "ML", "Web Development", "Problem Solving", "Team Collaboration"],
        "type": "hackathon",
        "stipend": "₹1,00,000 prize",
        "deadline": "2026-08-31",
        "url": "https://sih.gov.in",
    },
    {
        "title": "Google Summer of Code 2026",
        "company": "Google / Open Source",
        "location": "Remote",
        "description": "3-month open source contribution program. Work with ML orgs like TensorFlow, JAX, HuggingFace. Stipend varies by country.",
        "required_skills": ["Python", "Open Source", "Git", "ML", "Documentation", "Communication"],
        "type": "fellowship",
        "stipend": "$1,500 – $3,300",
        "deadline": "2026-04-02",
        "url": "https://summerofcode.withgoogle.com",
    },
    {
        "title": "Research Intern — Evaluation & Safety",
        "company": "Anthropic",
        "location": "Remote / San Francisco",
        "description": "Work on evaluating frontier AI models. Build evals, red-team models, and develop automated safety testing pipelines.",
        "required_skills": ["Python", "LLMs", "Evaluation", "Statistical Analysis", "Research", "RAGAS"],
        "type": "internship",
        "stipend": "$8,000/month",
        "deadline": "2026-09-01",
        "url": "https://anthropic.com/careers",
    },
    {
        "title": "ML Intern — Search Ranking",
        "company": "Swiggy",
        "location": "Bangalore, India",
        "description": "Improve food search and discovery ranking. Work on LTR models, bandit algorithms, and real-time personalization.",
        "required_skills": ["Python", "LightGBM", "LTR", "Bandit Algorithms", "SQL", "Spark", "A/B Testing"],
        "type": "internship",
        "stipend": "₹60,000/month",
        "deadline": "2026-07-31",
        "url": "https://swiggy.com/careers",
    },
    {
        "title": "AI Research Intern",
        "company": "Adobe India",
        "location": "Noida / Bangalore",
        "description": "Research generative AI for creative applications: image generation, style transfer, content-aware editing. Publish at top venues.",
        "required_skills": ["Python", "PyTorch", "Diffusion Models", "GANs", "Computer Vision", "Research"],
        "type": "internship",
        "stipend": "₹75,000/month",
        "deadline": "2026-08-31",
        "url": "https://adobe.com/careers",
    },
    {
        "title": "ML Intern — Risk & Fraud",
        "company": "Razorpay",
        "location": "Bangalore, India",
        "description": "Build real-time fraud detection models. Work on graph neural networks, anomaly detection, and high-throughput model serving.",
        "required_skills": ["Python", "GNNs", "Anomaly Detection", "Scikit-learn", "Kafka", "Redis", "SQL"],
        "type": "internship",
        "stipend": "₹65,000/month",
        "deadline": "2026-08-01",
        "url": "https://razorpay.com/jobs",
    },
    {
        "title": "Kaggle Grandmaster Fellowship",
        "company": "Kaggle / Google",
        "location": "Remote",
        "description": "Competitive ML fellowship for top Kaggle competitors. Work on real ML problems, access premium compute, mentorship from Googlers.",
        "required_skills": ["Python", "XGBoost", "Deep Learning", "Feature Engineering", "Kaggle", "EDA"],
        "type": "fellowship",
        "stipend": "$2,000/month",
        "deadline": "2026-10-01",
        "url": "https://kaggle.com/competitions",
    },
    {
        "title": "Deep Learning Research Intern",
        "company": "IISc IIIT Bangalore (RBCCPS)",
        "location": "Bangalore, India",
        "description": "Research on deep learning for robotics and autonomous systems. Work on perception, planning, and sim-to-real transfer.",
        "required_skills": ["Python", "PyTorch", "Deep Learning", "ROS", "Computer Vision", "Reinforcement Learning"],
        "type": "research",
        "stipend": "₹20,000/month",
        "deadline": "2026-08-01",
        "url": "https://rbccps.org",
    },
    {
        "title": "Applied ML Intern",
        "company": "Walmart Global Tech India",
        "location": "Bangalore, India",
        "description": "Build demand forecasting, assortment optimization, and pricing models at petabyte scale. Work with cutting-edge distributed ML systems.",
        "required_skills": ["Python", "Spark", "LightGBM", "Time Series", "SQL", "Airflow", "AWS"],
        "type": "internship",
        "stipend": "₹70,000/month",
        "deadline": "2026-07-20",
        "url": "https://walmart.com/careers",
    },
    {
        "title": "ML Intern — Personalisation",
        "company": "Myntra",
        "location": "Bangalore, India",
        "description": "Improve fashion recommendation and personalisation. Work on multi-modal models (image + text), bandit algorithms, and real-time serving.",
        "required_skills": ["Python", "PyTorch", "Recommender Systems", "Computer Vision", "NLP", "SQL"],
        "type": "internship",
        "stipend": "₹55,000/month",
        "deadline": "2026-08-15",
        "url": "https://myntra.com/careers",
    },
    {
        "title": "AI/ML Intern",
        "company": "Infosys Springboard",
        "location": "Pune / Hyderabad",
        "description": "Work with enterprise AI teams on predictive analytics, document understanding, and automated decision systems.",
        "required_skills": ["Python", "Machine Learning", "scikit-learn", "SQL", "REST APIs", "Git"],
        "type": "internship",
        "stipend": "₹30,000/month",
        "deadline": "2026-09-30",
        "url": "https://springboard.infosys.com",
    },
    {
        "title": "NLP Intern",
        "company": "Vernacular.ai",
        "location": "Bangalore, India",
        "description": "Build voice-first AI experiences in Indian languages. Work on ASR, TTS, dialogue systems, and intent classification.",
        "required_skills": ["Python", "NLP", "PyTorch", "Speech Processing", "Transformers", "HuggingFace"],
        "type": "internship",
        "stipend": "₹45,000/month",
        "deadline": "2026-08-31",
        "url": "https://vernacular.ai/careers",
    },
    {
        "title": "Data Science Intern — Growth",
        "company": "Zepto",
        "location": "Mumbai, India",
        "description": "Drive growth experiments through A/B testing, causal modelling, and predictive customer lifetime value models.",
        "required_skills": ["Python", "Statistics", "SQL", "Pandas", "A/B Testing", "Causal Inference", "Tableau"],
        "type": "internship",
        "stipend": "₹50,000/month",
        "deadline": "2026-07-31",
        "url": "https://www.zeptonow.com/careers",
    },
    {
        "title": "LLM Fine-Tuning Intern",
        "company": "Lexi (YC W24)",
        "location": "Remote",
        "description": "Fine-tune and align small language models for legal and finance domains. Work on LoRA, RLHF, and custom evaluation benchmarks.",
        "required_skills": ["Python", "PyTorch", "LLMs", "Fine-tuning", "LoRA", "HuggingFace", "PEFT"],
        "type": "internship",
        "stipend": "$2,500/month",
        "deadline": "2026-09-01",
        "url": "https://ycombinator.com",
    },
    {
        "title": "ML Intern — Healthcare AI",
        "company": "Niramai Health Analytix",
        "location": "Bangalore, India",
        "description": "Build medical image analysis models for early cancer detection using thermal imaging. FDA/CE compliance exposure included.",
        "required_skills": ["Python", "PyTorch", "Medical Imaging", "Computer Vision", "Deep Learning", "scikit-learn"],
        "type": "internship",
        "stipend": "₹35,000/month",
        "deadline": "2026-08-31",
        "url": "https://niramai.com/careers",
    },
    {
        "title": "Research Intern — Multimodal AI",
        "company": "IIT Bombay (C-MInDS)",
        "location": "Mumbai, India",
        "description": "Research on vision-language models, visual question answering, and image captioning for low-resource settings.",
        "required_skills": ["Python", "PyTorch", "Computer Vision", "NLP", "Transformers", "Research"],
        "type": "research",
        "stipend": "₹18,000/month",
        "deadline": "2026-08-01",
        "url": "https://www.minds.iitb.ac.in",
    },
    {
        "title": "MLOps Engineer Intern",
        "company": "Sigmoid",
        "location": "Bangalore / Remote",
        "description": "Build and maintain scalable ML pipelines, feature stores, and model monitoring systems for Fortune 100 clients.",
        "required_skills": ["Python", "Docker", "Kubernetes", "MLflow", "Airflow", "AWS", "GCP", "CI/CD"],
        "type": "internship",
        "stipend": "₹40,000/month",
        "deadline": "2026-09-15",
        "url": "https://sigmoid.com/careers",
    },
    {
        "title": "AI Hackathon — Bhashini Challenge",
        "company": "Ministry of Electronics (MeitY)",
        "location": "Delhi / Virtual",
        "description": "Build AI solutions for Indian language accessibility. Solve problems in translation, transliteration, ASR for 22 scheduled languages.",
        "required_skills": ["Python", "NLP", "Speech Processing", "Machine Translation", "FastAPI", "Docker"],
        "type": "hackathon",
        "stipend": "₹10,00,000 prize pool",
        "deadline": "2026-08-15",
        "url": "https://bhashini.gov.in",
    },
    {
        "title": "Quant ML Intern",
        "company": "Alphagrep Securities",
        "location": "Mumbai, India",
        "description": "Develop alpha signals using ML on high-frequency tick data. Research on time series, feature engineering for equity and derivatives markets.",
        "required_skills": ["Python", "NumPy", "Pandas", "Time Series", "Statistics", "SQL", "C++"],
        "type": "internship",
        "stipend": "₹80,000/month",
        "deadline": "2026-07-15",
        "url": "https://alphagrep.com",
    },
    {
        "title": "Generative AI Research Fellow",
        "company": "TIFR (Tata Institute of Fundamental Research)",
        "location": "Mumbai, India",
        "description": "6-month research fellowship at India's premier science institution. Work on theoretical aspects of generative models and score-based diffusion.",
        "required_skills": ["Python", "PyTorch", "Generative AI", "Diffusion Models", "Mathematics", "Research"],
        "type": "fellowship",
        "stipend": "₹30,000/month",
        "deadline": "2026-07-01",
        "url": "https://tifr.res.in",
    },
    {
        "title": "ML Platform Intern",
        "company": "PhonePe",
        "location": "Bangalore, India",
        "description": "Build the internal ML platform: feature pipelines, online inference, and model governance for 500M+ users.",
        "required_skills": ["Python", "Java", "Kafka", "Spark", "MLflow", "Docker", "SQL"],
        "type": "internship",
        "stipend": "₹75,000/month",
        "deadline": "2026-07-31",
        "url": "https://phonepe.com/careers",
    },
    {
        "title": "Deep Learning Intern — Edge AI",
        "company": "Bosch India",
        "location": "Coimbatore / Bangalore",
        "description": "Deploy neural networks on embedded automotive systems. Quantization, pruning, ONNX export, and TensorRT optimization.",
        "required_skills": ["Python", "PyTorch", "ONNX", "TensorRT", "Quantization", "Embedded Systems", "C++"],
        "type": "internship",
        "stipend": "₹40,000/month",
        "deadline": "2026-08-31",
        "url": "https://bosch.in/careers",
    },
    {
        "title": "Data Engineer Intern",
        "company": "Juspay",
        "location": "Bangalore, India",
        "description": "Build real-time data infrastructure for payments. Work on Flink streaming pipelines, data quality, and analytical dashboards.",
        "required_skills": ["Python", "SQL", "Apache Flink", "Kafka", "Spark", "dbt", "PostgreSQL"],
        "type": "internship",
        "stipend": "₹50,000/month",
        "deadline": "2026-08-01",
        "url": "https://juspay.in/careers",
    },
    {
        "title": "AI Safety Research Intern",
        "company": "Centre for AI Safety (CAIS)",
        "location": "Remote",
        "description": "Research on AI alignment, interpretability, and robustness. Work on mechanistic interpretability, red-teaming, and scalable oversight.",
        "required_skills": ["Python", "PyTorch", "LLMs", "Interpretability", "Research", "Statistics"],
        "type": "research",
        "stipend": "$3,000/month",
        "deadline": "2026-09-15",
        "url": "https://safe.ai",
    },
    {
        "title": "Intern — Conversational AI",
        "company": "Haptik (Jio Platforms)",
        "location": "Mumbai / Remote",
        "description": "Build enterprise chatbots and voice assistants. Work on dialogue management, entity recognition, and LLM-based intent systems.",
        "required_skills": ["Python", "NLP", "LLMs", "FastAPI", "Docker", "REST APIs", "SQL"],
        "type": "internship",
        "stipend": "₹40,000/month",
        "deadline": "2026-08-31",
        "url": "https://haptik.ai/careers",
    },
    {
        "title": "Kaggle x Google ML Bootcamp",
        "company": "Google India",
        "location": "Remote / Bangalore",
        "description": "8-week intensive ML upskilling programme with Kaggle competitions. Top performers get fast-tracked to Google ML internship interviews.",
        "required_skills": ["Python", "Machine Learning", "Deep Learning", "Kaggle", "TensorFlow"],
        "type": "fellowship",
        "stipend": "No stipend — certificate + referral",
        "deadline": "2026-07-31",
        "url": "https://developers.google.com/machine-learning/bootcamp",
    },
    {
        "title": "AI Research Intern",
        "company": "Samsung R&D India",
        "location": "Noida / Bangalore",
        "description": "Research on on-device AI, neural architecture search, and efficient inference for mobile platforms.",
        "required_skills": ["Python", "PyTorch", "NAS", "Quantization", "Computer Vision", "C++"],
        "type": "internship",
        "stipend": "₹60,000/month",
        "deadline": "2026-08-15",
        "url": "https://samsung.com/in/aboutsamsung/careers/",
    },
    {
        "title": "ML Intern — FinTech",
        "company": "CRED",
        "location": "Bangalore, India",
        "description": "Build credit risk, fraud detection, and spend analytics models for premium card users.",
        "required_skills": ["Python", "scikit-learn", "XGBoost", "SQL", "Pandas", "Statistics", "Feature Engineering"],
        "type": "internship",
        "stipend": "₹65,000/month",
        "deadline": "2026-08-31",
        "url": "https://cred.club/careers",
    },
    {
        "title": "Research Intern — Autonomous Driving",
        "company": "Ola Electric (Bhavish Aggarwal AI Lab)",
        "location": "Bangalore, India",
        "description": "Develop perception, prediction, and planning algorithms for two-wheeler autonomous driving. Work with sensor fusion and real-world test data.",
        "required_skills": ["Python", "PyTorch", "Computer Vision", "3D Object Detection", "LiDAR", "Sensor Fusion"],
        "type": "research",
        "stipend": "₹70,000/month",
        "deadline": "2026-07-31",
        "url": "https://olaelectric.com/careers",
    },
    {
        "title": "AI/ML Intern — AgriTech",
        "company": "Cropin Technology",
        "location": "Bangalore / Remote",
        "description": "Build crop yield prediction, disease detection, and satellite imagery analysis models for precision farming.",
        "required_skills": ["Python", "Machine Learning", "Satellite Imagery", "Computer Vision", "PyTorch", "GIS"],
        "type": "internship",
        "stipend": "₹35,000/month",
        "deadline": "2026-09-01",
        "url": "https://cropin.com/careers",
    },
    {
        "title": "Knowledge Graph Intern",
        "company": "TCS Research",
        "location": "Pune / Hyderabad",
        "description": "Build enterprise knowledge graphs for industrial IoT. Work on graph neural networks, ontologies, and SPARQL reasoning.",
        "required_skills": ["Python", "Graph Neural Networks", "Neo4j", "SPARQL", "NLP", "Knowledge Graphs"],
        "type": "research",
        "stipend": "₹25,000/month",
        "deadline": "2026-09-30",
        "url": "https://tcs.com/research",
    },
    {
        "title": "Open Source ML Intern",
        "company": "Hugging Face",
        "location": "Remote",
        "description": "Contribute to Transformers, Datasets, or PEFT libraries. Add model support, improve documentation, write blog posts on new research.",
        "required_skills": ["Python", "PyTorch", "Transformers", "HuggingFace", "Open Source", "Git", "LLMs"],
        "type": "internship",
        "stipend": "$3,500/month",
        "deadline": "2026-08-01",
        "url": "https://huggingface.co/jobs",
    },
    {
        "title": "Data Science Intern — HealthTech",
        "company": "Practo",
        "location": "Bangalore, India",
        "description": "Build NLP models for clinical note understanding, symptom extraction, and treatment recommendation.",
        "required_skills": ["Python", "NLP", "scikit-learn", "SQL", "Medical Text Mining", "Pandas"],
        "type": "internship",
        "stipend": "₹40,000/month",
        "deadline": "2026-08-31",
        "url": "https://practo.com/careers",
    },
    {
        "title": "Vector Search Intern",
        "company": "Qdrant (Remote)",
        "location": "Remote",
        "description": "Work on the Qdrant open-source vector database. Implement new distance metrics, improve ANN indexing, benchmark against competitors.",
        "required_skills": ["Python", "Rust", "Vector Databases", "Embeddings", "RAG", "Git", "Open Source"],
        "type": "internship",
        "stipend": "€2,500/month",
        "deadline": "2026-09-01",
        "url": "https://qdrant.tech/careers",
    },
    {
        "title": "AI Intern — EdTech",
        "company": "BYJU'S / Think & Learn",
        "location": "Bangalore, India",
        "description": "Personalise learning paths using RL and cognitive models. Build knowledge tracing, adaptive testing, and student dropout prediction.",
        "required_skills": ["Python", "Machine Learning", "Reinforcement Learning", "SQL", "scikit-learn", "Statistics"],
        "type": "internship",
        "stipend": "₹35,000/month",
        "deadline": "2026-09-30",
        "url": "https://byjus.com/careers",
    },
    {
        "title": "Research Intern — Foundation Models",
        "company": "IBM Research India",
        "location": "Bangalore, India",
        "description": "Work on efficient foundation model training, tokenisation for low-resource languages, and enterprise AI alignment.",
        "required_skills": ["Python", "PyTorch", "LLMs", "Fine-tuning", "Research", "Distributed Training"],
        "type": "research",
        "stipend": "₹50,000/month",
        "deadline": "2026-08-01",
        "url": "https://research.ibm.com/labs/india",
    },
    {
        "title": "AI for Social Good Fellowship",
        "company": "iSPIRT Foundation",
        "location": "Bangalore / Remote",
        "description": "Apply ML to public digital infrastructure: UPI fraud analytics, ABDM health data, ONDC recommendation systems.",
        "required_skills": ["Python", "Machine Learning", "Pandas", "SQL", "FastAPI", "Public Policy Interest"],
        "type": "fellowship",
        "stipend": "₹30,000/month",
        "deadline": "2026-08-31",
        "url": "https://ispirt.in",
    },
    {
        "title": "Agentic RAG Intern",
        "company": "Pesto Tech",
        "location": "Remote / Delhi",
        "description": "Build production RAG pipelines for enterprise document QA. Work with LangGraph, re-ranking, hybrid retrieval, and evaluation frameworks.",
        "required_skills": ["Python", "LangChain", "LangGraph", "RAG", "Vector Databases", "FastAPI", "LLMs"],
        "type": "internship",
        "stipend": "₹45,000/month",
        "deadline": "2026-09-15",
        "url": "https://pesto.tech",
    },
    {
        "title": "Time Series ML Intern",
        "company": "Tata Power",
        "location": "Mumbai / Remote",
        "description": "Forecast energy demand, detect equipment anomalies, and optimise power grid operations using ML on IoT sensor data.",
        "required_skills": ["Python", "Time Series", "PyTorch", "Pandas", "SQL", "Signal Processing"],
        "type": "internship",
        "stipend": "₹35,000/month",
        "deadline": "2026-09-30",
        "url": "https://tatapower.com/careers",
    },
]


async def seed():
    await init_db()
    async with AsyncSessionLocal() as db:
        for opp_data in OPPORTUNITIES:
            # Build embedding
            embed_text = f"{opp_data['title']} {opp_data['company']} {' '.join(opp_data['required_skills'])} {opp_data.get('description', '')}"
            embedding = await embedding_service.embed(embed_text)

            opp = Opportunity(**opp_data, embedding=embedding)
            db.add(opp)

        await db.commit()
        print(f"Seeded {len(OPPORTUNITIES)} opportunities.")


if __name__ == "__main__":
    asyncio.run(seed())
